package dto;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pay_order
 */
public class PayOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *   支付订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_order_no
     *
     * @mbg.generated
     */
    private String payOrderNo;

    /**
     *   支付渠道号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_channel_code
     *
     * @mbg.generated
     */
    private String payChannelCode;

    /**
     *   支付类型：1 表示代扣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_type
     *
     * @mbg.generated
     */
    private Integer payType;

    /**
     *   支付金额(分)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_amount
     *
     * @mbg.generated
     */
    private Integer payAmount;

    /**
     *   商户编号,支付系统提供，业务系统传入
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.merchant_code
     *
     * @mbg.generated
     */
    private String merchantCode;

    /**
     *   代扣重试时间(秒)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.last_withold_time
     *
     * @mbg.generated
     */
    private Integer lastWitholdTime;

    /**
     *   业务订单类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.business_order_type
     *
     * @mbg.generated
     */
    private String businessOrderType;

    /**
     *   业务订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.business_order_no
     *
     * @mbg.generated
     */
    private String businessOrderNo;

    /**
     *   支付结果回调url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.callback_url
     *
     * @mbg.generated
     */
    private String callbackUrl;

    /**
     *   前端请求URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.return_url
     *
     * @mbg.generated
     */
    private String returnUrl;

    /**
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.id_number
     *
     * @mbg.generated
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.bankcard_no
     *
     * @mbg.generated
     */
    private String bankcardNo;

    /**
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *   已付金额(分)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.deducted_amount
     *
     * @mbg.generated
     */
    private Integer deductedAmount;

    /**
     *   1 待支付  2 支付中  3 支付成功   4 支付失败  5 撤销支付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_state
     *
     * @mbg.generated
     */
    private Short payState;

    /**
     *   代扣拆分 no_split不拆分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.split_code
     *
     * @mbg.generated
     */
    private String splitCode;

    /**
     *   分账code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.divide_code
     *
     * @mbg.generated
     */
    private String divideCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.id
     *
     * @return the value of pay_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.id
     *
     * @param id the value for pay_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_order_no
     *
     * @return the value of pay_order.pay_order_no
     *
     * @mbg.generated
     */
    public String getPayOrderNo() {
        return payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_order_no
     *
     * @param payOrderNo the value for pay_order.pay_order_no
     *
     * @mbg.generated
     */
    public void setPayOrderNo(String payOrderNo) {
        this.payOrderNo = payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_channel_code
     *
     * @return the value of pay_order.pay_channel_code
     *
     * @mbg.generated
     */
    public String getPayChannelCode() {
        return payChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_channel_code
     *
     * @param payChannelCode the value for pay_order.pay_channel_code
     *
     * @mbg.generated
     */
    public void setPayChannelCode(String payChannelCode) {
        this.payChannelCode = payChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_type
     *
     * @return the value of pay_order.pay_type
     *
     * @mbg.generated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_type
     *
     * @param payType the value for pay_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_amount
     *
     * @return the value of pay_order.pay_amount
     *
     * @mbg.generated
     */
    public Integer getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_amount
     *
     * @param payAmount the value for pay_order.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(Integer payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.merchant_code
     *
     * @return the value of pay_order.merchant_code
     *
     * @mbg.generated
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.merchant_code
     *
     * @param merchantCode the value for pay_order.merchant_code
     *
     * @mbg.generated
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.last_withold_time
     *
     * @return the value of pay_order.last_withold_time
     *
     * @mbg.generated
     */
    public Integer getLastWitholdTime() {
        return lastWitholdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.last_withold_time
     *
     * @param lastWitholdTime the value for pay_order.last_withold_time
     *
     * @mbg.generated
     */
    public void setLastWitholdTime(Integer lastWitholdTime) {
        this.lastWitholdTime = lastWitholdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.business_order_type
     *
     * @return the value of pay_order.business_order_type
     *
     * @mbg.generated
     */
    public String getBusinessOrderType() {
        return businessOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.business_order_type
     *
     * @param businessOrderType the value for pay_order.business_order_type
     *
     * @mbg.generated
     */
    public void setBusinessOrderType(String businessOrderType) {
        this.businessOrderType = businessOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.business_order_no
     *
     * @return the value of pay_order.business_order_no
     *
     * @mbg.generated
     */
    public String getBusinessOrderNo() {
        return businessOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.business_order_no
     *
     * @param businessOrderNo the value for pay_order.business_order_no
     *
     * @mbg.generated
     */
    public void setBusinessOrderNo(String businessOrderNo) {
        this.businessOrderNo = businessOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.callback_url
     *
     * @return the value of pay_order.callback_url
     *
     * @mbg.generated
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.callback_url
     *
     * @param callbackUrl the value for pay_order.callback_url
     *
     * @mbg.generated
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.return_url
     *
     * @return the value of pay_order.return_url
     *
     * @mbg.generated
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.return_url
     *
     * @param returnUrl the value for pay_order.return_url
     *
     * @mbg.generated
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.id_number
     *
     * @return the value of pay_order.id_number
     *
     * @mbg.generated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.id_number
     *
     * @param idNumber the value for pay_order.id_number
     *
     * @mbg.generated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.bankcard_no
     *
     * @return the value of pay_order.bankcard_no
     *
     * @mbg.generated
     */
    public String getBankcardNo() {
        return bankcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.bankcard_no
     *
     * @param bankcardNo the value for pay_order.bankcard_no
     *
     * @mbg.generated
     */
    public void setBankcardNo(String bankcardNo) {
        this.bankcardNo = bankcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.mobile
     *
     * @return the value of pay_order.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.mobile
     *
     * @param mobile the value for pay_order.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.deducted_amount
     *
     * @return the value of pay_order.deducted_amount
     *
     * @mbg.generated
     */
    public Integer getDeductedAmount() {
        return deductedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.deducted_amount
     *
     * @param deductedAmount the value for pay_order.deducted_amount
     *
     * @mbg.generated
     */
    public void setDeductedAmount(Integer deductedAmount) {
        this.deductedAmount = deductedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_state
     *
     * @return the value of pay_order.pay_state
     *
     * @mbg.generated
     */
    public Short getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_state
     *
     * @param payState the value for pay_order.pay_state
     *
     * @mbg.generated
     */
    public void setPayState(Short payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.split_code
     *
     * @return the value of pay_order.split_code
     *
     * @mbg.generated
     */
    public String getSplitCode() {
        return splitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.split_code
     *
     * @param splitCode the value for pay_order.split_code
     *
     * @mbg.generated
     */
    public void setSplitCode(String splitCode) {
        this.splitCode = splitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.divide_code
     *
     * @return the value of pay_order.divide_code
     *
     * @mbg.generated
     */
    public String getDivideCode() {
        return divideCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.divide_code
     *
     * @param divideCode the value for pay_order.divide_code
     *
     * @mbg.generated
     */
    public void setDivideCode(String divideCode) {
        this.divideCode = divideCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.create_time
     *
     * @return the value of pay_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.create_time
     *
     * @param createTime the value for pay_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.update_time
     *
     * @return the value of pay_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.update_time
     *
     * @param updateTime the value for pay_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PayOrder other = (PayOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayOrderNo() == null ? other.getPayOrderNo() == null : this.getPayOrderNo().equals(other.getPayOrderNo()))
            && (this.getPayChannelCode() == null ? other.getPayChannelCode() == null : this.getPayChannelCode().equals(other.getPayChannelCode()))
            && (this.getPayType() == null ? other.getPayType() == null : this.getPayType().equals(other.getPayType()))
            && (this.getPayAmount() == null ? other.getPayAmount() == null : this.getPayAmount().equals(other.getPayAmount()))
            && (this.getMerchantCode() == null ? other.getMerchantCode() == null : this.getMerchantCode().equals(other.getMerchantCode()))
            && (this.getLastWitholdTime() == null ? other.getLastWitholdTime() == null : this.getLastWitholdTime().equals(other.getLastWitholdTime()))
            && (this.getBusinessOrderType() == null ? other.getBusinessOrderType() == null : this.getBusinessOrderType().equals(other.getBusinessOrderType()))
            && (this.getBusinessOrderNo() == null ? other.getBusinessOrderNo() == null : this.getBusinessOrderNo().equals(other.getBusinessOrderNo()))
            && (this.getCallbackUrl() == null ? other.getCallbackUrl() == null : this.getCallbackUrl().equals(other.getCallbackUrl()))
            && (this.getReturnUrl() == null ? other.getReturnUrl() == null : this.getReturnUrl().equals(other.getReturnUrl()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getBankcardNo() == null ? other.getBankcardNo() == null : this.getBankcardNo().equals(other.getBankcardNo()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getDeductedAmount() == null ? other.getDeductedAmount() == null : this.getDeductedAmount().equals(other.getDeductedAmount()))
            && (this.getPayState() == null ? other.getPayState() == null : this.getPayState().equals(other.getPayState()))
            && (this.getSplitCode() == null ? other.getSplitCode() == null : this.getSplitCode().equals(other.getSplitCode()))
            && (this.getDivideCode() == null ? other.getDivideCode() == null : this.getDivideCode().equals(other.getDivideCode()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayOrderNo() == null) ? 0 : getPayOrderNo().hashCode());
        result = prime * result + ((getPayChannelCode() == null) ? 0 : getPayChannelCode().hashCode());
        result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
        result = prime * result + ((getPayAmount() == null) ? 0 : getPayAmount().hashCode());
        result = prime * result + ((getMerchantCode() == null) ? 0 : getMerchantCode().hashCode());
        result = prime * result + ((getLastWitholdTime() == null) ? 0 : getLastWitholdTime().hashCode());
        result = prime * result + ((getBusinessOrderType() == null) ? 0 : getBusinessOrderType().hashCode());
        result = prime * result + ((getBusinessOrderNo() == null) ? 0 : getBusinessOrderNo().hashCode());
        result = prime * result + ((getCallbackUrl() == null) ? 0 : getCallbackUrl().hashCode());
        result = prime * result + ((getReturnUrl() == null) ? 0 : getReturnUrl().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getBankcardNo() == null) ? 0 : getBankcardNo().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getDeductedAmount() == null) ? 0 : getDeductedAmount().hashCode());
        result = prime * result + ((getPayState() == null) ? 0 : getPayState().hashCode());
        result = prime * result + ((getSplitCode() == null) ? 0 : getSplitCode().hashCode());
        result = prime * result + ((getDivideCode() == null) ? 0 : getDivideCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payOrderNo=").append(payOrderNo);
        sb.append(", payChannelCode=").append(payChannelCode);
        sb.append(", payType=").append(payType);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", merchantCode=").append(merchantCode);
        sb.append(", lastWitholdTime=").append(lastWitholdTime);
        sb.append(", businessOrderType=").append(businessOrderType);
        sb.append(", businessOrderNo=").append(businessOrderNo);
        sb.append(", callbackUrl=").append(callbackUrl);
        sb.append(", returnUrl=").append(returnUrl);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", bankcardNo=").append(bankcardNo);
        sb.append(", mobile=").append(mobile);
        sb.append(", deductedAmount=").append(deductedAmount);
        sb.append(", payState=").append(payState);
        sb.append(", splitCode=").append(splitCode);
        sb.append(", divideCode=").append(divideCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}