package dto;

import com.esotericsoftware.kryo.DefaultSerializer;
import com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table car_driving_info
 */
/**
* DrivingInfo测试下注释compatibleFieldSerializer
* Auto generated by cx
*/
@DefaultSerializer(CompatibleFieldSerializer.class)
public class DrivingInfo implements Serializable {
    /**
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_driving_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *   车架号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_driving_info.vin_number
     *
     * @mbg.generated
     */
    private String vinNumber;

    /**
     *   发动机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_driving_info.engine_number
     *
     * @mbg.generated
     */
    private String engineNumber;

    /**
     *   乐车邦车型ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_driving_info.model_type
     *
     * @mbg.generated
     */
    private String modelType;

    /**
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_driving_info.created_time
     *
     * @mbg.generated
     */
    private Long createdTime;

    /**
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_driving_info.updated_time
     *
     * @mbg.generated
     */
    private Long updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_driving_info.id
     *
     * @return the value of car_driving_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_driving_info.id
     *
     * @param id the value for car_driving_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_driving_info.vin_number
     *
     * @return the value of car_driving_info.vin_number
     *
     * @mbg.generated
     */
    public String getVinNumber() {
        return vinNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_driving_info.vin_number
     *
     * @param vinNumber the value for car_driving_info.vin_number
     *
     * @mbg.generated
     */
    public void setVinNumber(String vinNumber) {
        this.vinNumber = vinNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_driving_info.engine_number
     *
     * @return the value of car_driving_info.engine_number
     *
     * @mbg.generated
     */
    public String getEngineNumber() {
        return engineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_driving_info.engine_number
     *
     * @param engineNumber the value for car_driving_info.engine_number
     *
     * @mbg.generated
     */
    public void setEngineNumber(String engineNumber) {
        this.engineNumber = engineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_driving_info.model_type
     *
     * @return the value of car_driving_info.model_type
     *
     * @mbg.generated
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_driving_info.model_type
     *
     * @param modelType the value for car_driving_info.model_type
     *
     * @mbg.generated
     */
    public void setModelType(String modelType) {
        this.modelType = modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_driving_info.created_time
     *
     * @return the value of car_driving_info.created_time
     *
     * @mbg.generated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_driving_info.created_time
     *
     * @param createdTime the value for car_driving_info.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_driving_info.updated_time
     *
     * @return the value of car_driving_info.updated_time
     *
     * @mbg.generated
     */
    public Long getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_driving_info.updated_time
     *
     * @param updatedTime the value for car_driving_info.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DrivingInfo other = (DrivingInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVinNumber() == null ? other.getVinNumber() == null : this.getVinNumber().equals(other.getVinNumber()))
            && (this.getEngineNumber() == null ? other.getEngineNumber() == null : this.getEngineNumber().equals(other.getEngineNumber()))
            && (this.getModelType() == null ? other.getModelType() == null : this.getModelType().equals(other.getModelType()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVinNumber() == null) ? 0 : getVinNumber().hashCode());
        result = prime * result + ((getEngineNumber() == null) ? 0 : getEngineNumber().hashCode());
        result = prime * result + ((getModelType() == null) ? 0 : getModelType().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", vinNumber=").append(vinNumber);
        sb.append(", engineNumber=").append(engineNumber);
        sb.append(", modelType=").append(modelType);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}