package dao;

import dto.DrivingInfo;
import exampleModel.DrivingInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrivingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    long countByExample(DrivingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    int deleteByExample(DrivingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    int insert(DrivingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    int insertSelective(DrivingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    List<DrivingInfo> selectByExample(DrivingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    DrivingInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DrivingInfo record, @Param("example") DrivingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DrivingInfo record, @Param("example") DrivingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DrivingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_driving_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DrivingInfo record);
}