package exampleModel;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PayOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public PayOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIsNull() {
            addCriterion("pay_order_no is null");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIsNotNull() {
            addCriterion("pay_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoEqualTo(String value) {
            addCriterion("pay_order_no =", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotEqualTo(String value) {
            addCriterion("pay_order_no <>", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoGreaterThan(String value) {
            addCriterion("pay_order_no >", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("pay_order_no >=", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoLessThan(String value) {
            addCriterion("pay_order_no <", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoLessThanOrEqualTo(String value) {
            addCriterion("pay_order_no <=", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoLike(String value) {
            addCriterion("pay_order_no like", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotLike(String value) {
            addCriterion("pay_order_no not like", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIn(List<String> values) {
            addCriterion("pay_order_no in", values, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotIn(List<String> values) {
            addCriterion("pay_order_no not in", values, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoBetween(String value1, String value2) {
            addCriterion("pay_order_no between", value1, value2, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotBetween(String value1, String value2) {
            addCriterion("pay_order_no not between", value1, value2, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeIsNull() {
            addCriterion("pay_channel_code is null");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeIsNotNull() {
            addCriterion("pay_channel_code is not null");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeEqualTo(String value) {
            addCriterion("pay_channel_code =", value, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeNotEqualTo(String value) {
            addCriterion("pay_channel_code <>", value, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeGreaterThan(String value) {
            addCriterion("pay_channel_code >", value, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pay_channel_code >=", value, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeLessThan(String value) {
            addCriterion("pay_channel_code <", value, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("pay_channel_code <=", value, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeLike(String value) {
            addCriterion("pay_channel_code like", value, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeNotLike(String value) {
            addCriterion("pay_channel_code not like", value, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeIn(List<String> values) {
            addCriterion("pay_channel_code in", values, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeNotIn(List<String> values) {
            addCriterion("pay_channel_code not in", values, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeBetween(String value1, String value2) {
            addCriterion("pay_channel_code between", value1, value2, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayChannelCodeNotBetween(String value1, String value2) {
            addCriterion("pay_channel_code not between", value1, value2, "payChannelCode");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("pay_type is null");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("pay_type is not null");
            return (Criteria) this;
        }

        public Criteria andPayTypeEqualTo(Integer value) {
            addCriterion("pay_type =", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotEqualTo(Integer value) {
            addCriterion("pay_type <>", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThan(Integer value) {
            addCriterion("pay_type >", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_type >=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThan(Integer value) {
            addCriterion("pay_type <", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_type <=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIn(List<Integer> values) {
            addCriterion("pay_type in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotIn(List<Integer> values) {
            addCriterion("pay_type not in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeBetween(Integer value1, Integer value2) {
            addCriterion("pay_type between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_type not between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNull() {
            addCriterion("pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNotNull() {
            addCriterion("pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPayAmountEqualTo(Integer value) {
            addCriterion("pay_amount =", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotEqualTo(Integer value) {
            addCriterion("pay_amount <>", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThan(Integer value) {
            addCriterion("pay_amount >", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_amount >=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThan(Integer value) {
            addCriterion("pay_amount <", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThanOrEqualTo(Integer value) {
            addCriterion("pay_amount <=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountIn(List<Integer> values) {
            addCriterion("pay_amount in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotIn(List<Integer> values) {
            addCriterion("pay_amount not in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountBetween(Integer value1, Integer value2) {
            addCriterion("pay_amount between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_amount not between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIsNull() {
            addCriterion("merchant_code is null");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIsNotNull() {
            addCriterion("merchant_code is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeEqualTo(String value) {
            addCriterion("merchant_code =", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotEqualTo(String value) {
            addCriterion("merchant_code <>", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeGreaterThan(String value) {
            addCriterion("merchant_code >", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_code >=", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLessThan(String value) {
            addCriterion("merchant_code <", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLessThanOrEqualTo(String value) {
            addCriterion("merchant_code <=", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLike(String value) {
            addCriterion("merchant_code like", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotLike(String value) {
            addCriterion("merchant_code not like", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIn(List<String> values) {
            addCriterion("merchant_code in", values, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotIn(List<String> values) {
            addCriterion("merchant_code not in", values, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeBetween(String value1, String value2) {
            addCriterion("merchant_code between", value1, value2, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotBetween(String value1, String value2) {
            addCriterion("merchant_code not between", value1, value2, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeIsNull() {
            addCriterion("last_withold_time is null");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeIsNotNull() {
            addCriterion("last_withold_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeEqualTo(Integer value) {
            addCriterion("last_withold_time =", value, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeNotEqualTo(Integer value) {
            addCriterion("last_withold_time <>", value, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeGreaterThan(Integer value) {
            addCriterion("last_withold_time >", value, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_withold_time >=", value, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeLessThan(Integer value) {
            addCriterion("last_withold_time <", value, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeLessThanOrEqualTo(Integer value) {
            addCriterion("last_withold_time <=", value, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeIn(List<Integer> values) {
            addCriterion("last_withold_time in", values, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeNotIn(List<Integer> values) {
            addCriterion("last_withold_time not in", values, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeBetween(Integer value1, Integer value2) {
            addCriterion("last_withold_time between", value1, value2, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andLastWitholdTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("last_withold_time not between", value1, value2, "lastWitholdTime");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeIsNull() {
            addCriterion("business_order_type is null");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeIsNotNull() {
            addCriterion("business_order_type is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeEqualTo(String value) {
            addCriterion("business_order_type =", value, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeNotEqualTo(String value) {
            addCriterion("business_order_type <>", value, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeGreaterThan(String value) {
            addCriterion("business_order_type >", value, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("business_order_type >=", value, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeLessThan(String value) {
            addCriterion("business_order_type <", value, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("business_order_type <=", value, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeLike(String value) {
            addCriterion("business_order_type like", value, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeNotLike(String value) {
            addCriterion("business_order_type not like", value, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeIn(List<String> values) {
            addCriterion("business_order_type in", values, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeNotIn(List<String> values) {
            addCriterion("business_order_type not in", values, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeBetween(String value1, String value2) {
            addCriterion("business_order_type between", value1, value2, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderTypeNotBetween(String value1, String value2) {
            addCriterion("business_order_type not between", value1, value2, "businessOrderType");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoIsNull() {
            addCriterion("business_order_no is null");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoIsNotNull() {
            addCriterion("business_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoEqualTo(String value) {
            addCriterion("business_order_no =", value, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoNotEqualTo(String value) {
            addCriterion("business_order_no <>", value, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoGreaterThan(String value) {
            addCriterion("business_order_no >", value, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("business_order_no >=", value, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoLessThan(String value) {
            addCriterion("business_order_no <", value, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoLessThanOrEqualTo(String value) {
            addCriterion("business_order_no <=", value, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoLike(String value) {
            addCriterion("business_order_no like", value, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoNotLike(String value) {
            addCriterion("business_order_no not like", value, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoIn(List<String> values) {
            addCriterion("business_order_no in", values, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoNotIn(List<String> values) {
            addCriterion("business_order_no not in", values, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoBetween(String value1, String value2) {
            addCriterion("business_order_no between", value1, value2, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusinessOrderNoNotBetween(String value1, String value2) {
            addCriterion("business_order_no not between", value1, value2, "businessOrderNo");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlIsNull() {
            addCriterion("callback_url is null");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlIsNotNull() {
            addCriterion("callback_url is not null");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlEqualTo(String value) {
            addCriterion("callback_url =", value, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlNotEqualTo(String value) {
            addCriterion("callback_url <>", value, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlGreaterThan(String value) {
            addCriterion("callback_url >", value, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlGreaterThanOrEqualTo(String value) {
            addCriterion("callback_url >=", value, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlLessThan(String value) {
            addCriterion("callback_url <", value, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlLessThanOrEqualTo(String value) {
            addCriterion("callback_url <=", value, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlLike(String value) {
            addCriterion("callback_url like", value, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlNotLike(String value) {
            addCriterion("callback_url not like", value, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlIn(List<String> values) {
            addCriterion("callback_url in", values, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlNotIn(List<String> values) {
            addCriterion("callback_url not in", values, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlBetween(String value1, String value2) {
            addCriterion("callback_url between", value1, value2, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackUrlNotBetween(String value1, String value2) {
            addCriterion("callback_url not between", value1, value2, "callbackUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlIsNull() {
            addCriterion("return_url is null");
            return (Criteria) this;
        }

        public Criteria andReturnUrlIsNotNull() {
            addCriterion("return_url is not null");
            return (Criteria) this;
        }

        public Criteria andReturnUrlEqualTo(String value) {
            addCriterion("return_url =", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlNotEqualTo(String value) {
            addCriterion("return_url <>", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlGreaterThan(String value) {
            addCriterion("return_url >", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlGreaterThanOrEqualTo(String value) {
            addCriterion("return_url >=", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlLessThan(String value) {
            addCriterion("return_url <", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlLessThanOrEqualTo(String value) {
            addCriterion("return_url <=", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlLike(String value) {
            addCriterion("return_url like", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlNotLike(String value) {
            addCriterion("return_url not like", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlIn(List<String> values) {
            addCriterion("return_url in", values, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlNotIn(List<String> values) {
            addCriterion("return_url not in", values, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlBetween(String value1, String value2) {
            addCriterion("return_url between", value1, value2, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlNotBetween(String value1, String value2) {
            addCriterion("return_url not between", value1, value2, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("id_number is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("id_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("id_number =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("id_number <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("id_number >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("id_number >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("id_number <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("id_number <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("id_number like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("id_number not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("id_number in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("id_number not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("id_number between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("id_number not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andBankcardNoIsNull() {
            addCriterion("bankcard_no is null");
            return (Criteria) this;
        }

        public Criteria andBankcardNoIsNotNull() {
            addCriterion("bankcard_no is not null");
            return (Criteria) this;
        }

        public Criteria andBankcardNoEqualTo(String value) {
            addCriterion("bankcard_no =", value, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoNotEqualTo(String value) {
            addCriterion("bankcard_no <>", value, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoGreaterThan(String value) {
            addCriterion("bankcard_no >", value, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoGreaterThanOrEqualTo(String value) {
            addCriterion("bankcard_no >=", value, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoLessThan(String value) {
            addCriterion("bankcard_no <", value, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoLessThanOrEqualTo(String value) {
            addCriterion("bankcard_no <=", value, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoLike(String value) {
            addCriterion("bankcard_no like", value, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoNotLike(String value) {
            addCriterion("bankcard_no not like", value, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoIn(List<String> values) {
            addCriterion("bankcard_no in", values, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoNotIn(List<String> values) {
            addCriterion("bankcard_no not in", values, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoBetween(String value1, String value2) {
            addCriterion("bankcard_no between", value1, value2, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andBankcardNoNotBetween(String value1, String value2) {
            addCriterion("bankcard_no not between", value1, value2, "bankcardNo");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountIsNull() {
            addCriterion("deducted_amount is null");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountIsNotNull() {
            addCriterion("deducted_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountEqualTo(Integer value) {
            addCriterion("deducted_amount =", value, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountNotEqualTo(Integer value) {
            addCriterion("deducted_amount <>", value, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountGreaterThan(Integer value) {
            addCriterion("deducted_amount >", value, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("deducted_amount >=", value, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountLessThan(Integer value) {
            addCriterion("deducted_amount <", value, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountLessThanOrEqualTo(Integer value) {
            addCriterion("deducted_amount <=", value, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountIn(List<Integer> values) {
            addCriterion("deducted_amount in", values, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountNotIn(List<Integer> values) {
            addCriterion("deducted_amount not in", values, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountBetween(Integer value1, Integer value2) {
            addCriterion("deducted_amount between", value1, value2, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andDeductedAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("deducted_amount not between", value1, value2, "deductedAmount");
            return (Criteria) this;
        }

        public Criteria andPayStateIsNull() {
            addCriterion("pay_state is null");
            return (Criteria) this;
        }

        public Criteria andPayStateIsNotNull() {
            addCriterion("pay_state is not null");
            return (Criteria) this;
        }

        public Criteria andPayStateEqualTo(Short value) {
            addCriterion("pay_state =", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotEqualTo(Short value) {
            addCriterion("pay_state <>", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateGreaterThan(Short value) {
            addCriterion("pay_state >", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateGreaterThanOrEqualTo(Short value) {
            addCriterion("pay_state >=", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateLessThan(Short value) {
            addCriterion("pay_state <", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateLessThanOrEqualTo(Short value) {
            addCriterion("pay_state <=", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateIn(List<Short> values) {
            addCriterion("pay_state in", values, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotIn(List<Short> values) {
            addCriterion("pay_state not in", values, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateBetween(Short value1, Short value2) {
            addCriterion("pay_state between", value1, value2, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotBetween(Short value1, Short value2) {
            addCriterion("pay_state not between", value1, value2, "payState");
            return (Criteria) this;
        }

        public Criteria andSplitCodeIsNull() {
            addCriterion("split_code is null");
            return (Criteria) this;
        }

        public Criteria andSplitCodeIsNotNull() {
            addCriterion("split_code is not null");
            return (Criteria) this;
        }

        public Criteria andSplitCodeEqualTo(String value) {
            addCriterion("split_code =", value, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeNotEqualTo(String value) {
            addCriterion("split_code <>", value, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeGreaterThan(String value) {
            addCriterion("split_code >", value, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("split_code >=", value, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeLessThan(String value) {
            addCriterion("split_code <", value, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeLessThanOrEqualTo(String value) {
            addCriterion("split_code <=", value, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeLike(String value) {
            addCriterion("split_code like", value, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeNotLike(String value) {
            addCriterion("split_code not like", value, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeIn(List<String> values) {
            addCriterion("split_code in", values, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeNotIn(List<String> values) {
            addCriterion("split_code not in", values, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeBetween(String value1, String value2) {
            addCriterion("split_code between", value1, value2, "splitCode");
            return (Criteria) this;
        }

        public Criteria andSplitCodeNotBetween(String value1, String value2) {
            addCriterion("split_code not between", value1, value2, "splitCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeIsNull() {
            addCriterion("divide_code is null");
            return (Criteria) this;
        }

        public Criteria andDivideCodeIsNotNull() {
            addCriterion("divide_code is not null");
            return (Criteria) this;
        }

        public Criteria andDivideCodeEqualTo(String value) {
            addCriterion("divide_code =", value, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeNotEqualTo(String value) {
            addCriterion("divide_code <>", value, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeGreaterThan(String value) {
            addCriterion("divide_code >", value, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeGreaterThanOrEqualTo(String value) {
            addCriterion("divide_code >=", value, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeLessThan(String value) {
            addCriterion("divide_code <", value, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeLessThanOrEqualTo(String value) {
            addCriterion("divide_code <=", value, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeLike(String value) {
            addCriterion("divide_code like", value, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeNotLike(String value) {
            addCriterion("divide_code not like", value, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeIn(List<String> values) {
            addCriterion("divide_code in", values, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeNotIn(List<String> values) {
            addCriterion("divide_code not in", values, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeBetween(String value1, String value2) {
            addCriterion("divide_code between", value1, value2, "divideCode");
            return (Criteria) this;
        }

        public Criteria andDivideCodeNotBetween(String value1, String value2) {
            addCriterion("divide_code not between", value1, value2, "divideCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}